source 'https://rubygems.org'
ruby "2.3.1"

gem 'rails',        '~> 4.2.7.1'
gem 'coffee-rails', '~> 4.0.0'
gem "react_on_rails", "~> 6"
gem 'redis-rails',  '~> 4.0.0'
gem 'mini_racer'
gem 'sass-rails',   '~> 4.0.5'
gem 'protected_attributes'
gem 'mysql2', '~> 0.4.4'
gem 'compass-rails'
gem 'activeresource', '4.1.0'
gem 'ejs', '1.1.1'
gem 'eco', '1.0.0'

gem 'bootstrap-sass', '3.1.1.0' #keep at 3.1.x until upgrading rails to 4.x

gem 'autoprefixer-rails'
gem 'newrelic_plugin'
gem 'net-ssh', '>= 2.9.2'
gem 'ruby-mass'
gem 'twilio-ruby', '~> 3.11'
gem 'lob', '~> 2.4'
gem "StreetAddress"
gem 'paranoia', '~> 2.0'
gem 'ruby-saml', '~> 1.3.0'
#gem 'devise_saml_authenticatable' #only supports Rails 4.x
gem 'ruby-saml-idp'
gem 'ruby-openid'
gem 'openid_ar_store', git: 'https://github.com/kremez19/openid-ar-store.git'
gem 'httparty'
gem 'htmlentities'
gem 'smarter_csv'
gem 'ruby-stemmer'
gem 'yui-compressor'
gem 'closure-compiler'
gem 'coffee-script-source', '1.4.0'
gem 'haml_coffee_assets', '~> 1.16.2'
gem 'anbt-sql-formatter'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'execjs'
gem 'uglifier', '>= 2.2.1'
gem 'oily_png', '~> 1.0.2'
gem 'RubyInlineWithoutZenTest'
gem 'png'
gem 'rqrcode-with-patches', '~> 0.5.4' # For Generating QR Codes
gem 'mini_magick', '~> 4.8.0'
gem 'rest-client', '~> 1.8.0'
gem 'simple_hl7', '~> 1.0.2'
gem 'ruby-hl7', '~> 1.1.1'
gem 'httpclient', '~> 2.8.2.4'
gem 'excon', '0.71.0'
gem 'savon', '~> 2.11.1'  # SOAP Client for HL7/Immunization requests
gem 'daemons', '1.1.9'
gem 'sidekiq', '~> 5.0.4'
gem 'attentive_sidekiq'
gem "sidekiq-cron", "~> 0.6.3"
gem 'attr_encrypted', '~> 1.3.5'
gem 'logglier', '0.5.0'
gem 'syslogger', '1.6.0'
gem 'lograge'
gem 'date_validator'
gem 'request_store'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

# AWS
gem 'unicorn', '~> 5.0'
gem 'unicorn-worker-killer', git: 'https://github.com/reverbdotcom/unicorn-worker-killer.git'
gem 'asset_sync'
gem 'fog', '1.28.0' # dep of asset_sync
gem "bugsnag"
gem 'newrelic_rpm'
gem 'ddtrace'
gem 'dogapi', '~> 1.3.0'
gem 'sendgrid'


gem 'paperclip', "~> 5.0.0"
gem 'aws-sdk', '~> 2' # use AWS.eager_autoload! for thread safety
gem 'rabl'
gem 'devise'
gem 'devise-token_authenticatable'
gem 'devise-encryptable'
gem 'net-ldap'
gem 'workflow'
gem 'faraday'
gem 'faraday_middleware'
gem 'faraday_middleware-aws-signers-v4'
gem 'elasticsearch', '~> 2.0.0'
gem 'elasticsearch-model', '~> 0.1.9'
gem 'elasticsearch-rails', '~> 0.1.9'
gem 'will_paginate'
gem 'prawn', '~> 1.0.0'
gem 'pdf-forms'
gem 'origami'
gem 'apipie-rails'
gem 'faker'
gem 'cancancan', '1.15.0'
gem 'doorkeeper', '~> 4.2.0'
gem 'oj'
gem 'active_subset_validator'
gem 'haml'
gem 'i18n'
gem 'pundit'
gem 'unf'
gem 'coveralls', require: false
gem 'paper_trail', '~> 7.1.1'
gem 'kmts', '~> 2.0.0'
gem 'validates_phone_number'
gem 'friendly_id', '~> 5.1.0'
gem 'ruby_ICE_client', '>= 0.0.4'
gem 'progress_bar'
gem 'rbtrace'
gem 'attribute_normalizer'

gem 'oauth2', require: false
gem 'roadie-rails', '~> 1.0' # inline css injection to actionmailer email layouts
gem 'business' # Date calculations based on business calendars
gem 'hoe'

group :development do
  gem 'active_record_query_trace'
  gem 'awesome_print'
  gem 'pry-rails'
  gem 'rails_best_practices', require: false
  gem 'hirb', require: false
  gem 'rack-mini-profiler', '~> 0.10.1', require: false
  gem 'quiet_assets'
  gem 'letter_opener_web', '~> 1.2.0'
  gem 'foreman'
  gem 'memory_profiler'

  gem 'capistrano', '~> 3.0', require: false
  gem 'capistrano-rails',   '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'capistrano-rvm', require: false
  gem 'slackistrano'
  gem 'rerun'
end

group :profile do
  gem 'ruby-prof'
end

group :test, :production do
  #These libs for QR code/phaxio support can cause issues on Mac OS X and with upgrades to gcc or other system libraries
  #gem 'gdk_pixbuf2', '~> 2.1.0'
  #gem 'glib2', '~> 2.1.0'
  #gem 'cairo', '~> 1.12.8'
  #gem 'poppler', '~> 2.1.0'
  #gem "zbar", "~> 0.2.2"                 # For Scanning QR Codes
end

group :test, :development do
  gem 'pry-byebug', '~> 3.4'
  gem 'rspec-rails', '3.5.2'
  gem 'byebug'
  gem 'cane'
  gem 'rspec-console'
  gem 'rspec-retry'
  gem 'brakeman','3.3.5', :require => false
  gem 'guard'
  gem 'guard-rubocop'
  gem 'spring'
  gem 'rubocop', require: false
end

group :test do
  gem "pdf-inspector"
  gem "factory_girl_rails"
  gem "capybara", '~> 2.15.0'
  gem "rspec-collection_matchers"
  gem "shoulda-matchers", '2.8.0'
  gem "guard-rspec"
  gem 'database_cleaner', "~> 1.0.0"
  gem 'rb-fsevent', require: false
  gem 'rspec-instafail'
  gem 'selenium-webdriver', "~> 3.5.0"
  gem 'poltergeist', '1.5.0'
  gem 'timecop'
  gem 'rspec_junit_formatter'
  gem 'concurrent-ruby'
end
